<?php

use Illuminate\Database\Seeder;

use App\Models\Timezone;

class TimezoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $timezoneList =     [
            ['status' => 0, 'offset'  => '-11:00', 'label'  => '(GMT-11:00) Niue', 'timezone'  => 'Pacific/Niue'],
            ['status' => 0, 'offset'  => '-11:00', 'label'  => '(GMT-11:00) Pago Pago', 'timezone'  => 'Pacific/Pago_Pago'],
            ['status' => 1, 'offset'  => '-10:00', 'label'  => '(GMT-10:00) Hawaii Time', 'timezone'  => 'Pacific/Honolulu'],
            ['status' => 1, 'offset'  => '-10:00', 'label'  => '(GMT-10:00) Rarotonga', 'timezone'  => 'Pacific/Rarotonga'],
            ['status' => 1, 'offset'  => '-10:00', 'label'  => '(GMT-10:00) Tahiti', 'timezone'  => 'Pacific/Tahiti'],
            ['status' => 1, 'offset'  => '-09:30', 'label'  => '(GMT-09:30) Marquesas', 'timezone'  => 'Pacific/Marquesas'],
            ['status' => 1, 'offset'  => '-09:00', 'label'  => '(GMT-09:00) Alaska Time', 'timezone'  => 'America/Anchorage'],
            ['status' => 1, 'offset'  => '-09:00', 'label'  => '(GMT-09:00) Gambier', 'timezone'  => 'Pacific/Gambier'],
            ['status' => 1, 'offset'  => '-08:00', 'label'  => '(GMT-08:00) Pacific Time', 'timezone'  => 'America/Los_Angeles'],
            ['status' => 1, 'offset'  => '-08:00', 'label'  => '(GMT-08:00) Pacific Time - Tijuana', 'timezone'  => 'America/Tijuana'],
            ['status' => 1, 'offset'  => '-08:00', 'label'  => '(GMT-08:00) Pacific Time - Vancouver', 'timezone'  => 'America/Vancouver'],
            ['status' => 1, 'offset'  => '-08:00', 'label'  => '(GMT-08:00) Pacific Time - Whitehorse', 'timezone'  => 'America/Whitehorse'],
            ['status' => 1, 'offset'  => '-08:00', 'label'  => '(GMT-08:00) Pitcairn', 'timezone'  => 'Pacific/Pitcairn'],
            ['status' => 1, 'offset'  => '-07:00', 'label'  => '(GMT-07:00) Mountain Time', 'timezone'  => 'America/Denver'],
            ['status' => 1, 'offset'  => '-07:00', 'label'  => '(GMT-07:00) Mountain Time - Arizona', 'timezone'  => 'America/Phoenix'],
            ['status' => 1, 'offset'  => '-07:00', 'label'  => '(GMT-07:00) Mountain Time - Chihuahua, Mazatlan', 'timezone'  => 'America/Mazatlan'],
            ['status' => 1, 'offset'  => '-07:00', 'label'  => '(GMT-07:00) Mountain Time - Dawson Creek', 'timezone'  => 'America/Dawson_Creek'],
            ['status' => 1, 'offset'  => '-07:00', 'label'  => '(GMT-07:00) Mountain Time - Edmonton', 'timezone'  => 'America/Edmonton'],
            ['status' => 1, 'offset'  => '-07:00', 'label'  => '(GMT-07:00) Mountain Time - Hermosillo', 'timezone'  => 'America/Hermosillo'],
            ['status' => 1, 'offset'  => '-07:00', 'label'  => '(GMT-07:00) Mountain Time - Yellowknife', 'timezone'  => 'America/Yellowknife'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) Belize', 'timezone'  => 'America/Belize'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) Central Time', 'timezone'  => 'America/Chicago'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) Central Time - Mexico City', 'timezone'  => 'America/Mexico_City'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) Central Time - Regina', 'timezone'  => 'America/Regina'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) Central Time - Tegucigalpa', 'timezone'  => 'America/Tegucigalpa'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) Central Time - Winnipeg', 'timezone'  => 'America/Winnipeg'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) Costa Rica', 'timezone'  => 'America/Costa_Rica'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) El Salvador', 'timezone'  => 'America/El_Salvador'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) Galapagos', 'timezone'  => 'Pacific/Galapagos'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) Guatemala', 'timezone'  => 'America/Guatemala'],
            ['status' => 1, 'offset'  => '-06:00', 'label'  => '(GMT-06:00) Managua', 'timezone'  => 'America/Managua'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) America Cancun', 'timezone'  => 'America/Cancun'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Bogota', 'timezone'  => 'America/Bogota'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Easter Island', 'timezone'  => 'Pacific/Easter'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Eastern Time', 'timezone'  => 'America/New_York'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Eastern Time - Iqaluit', 'timezone'  => 'America/Iqaluit'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Eastern Time - Toronto', 'timezone'  => 'America/Toronto'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Guayaquil', 'timezone'  => 'America/Guayaquil'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Havana', 'timezone'  => 'America/Havana'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Jamaica', 'timezone'  => 'America/Jamaica'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Lima', 'timezone'  => 'America/Lima'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Nassau', 'timezone'  => 'America/Nassau'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Panama', 'timezone'  => 'America/Panama'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Port-au-Prince', 'timezone'  => 'America/Port-au-Prince'],
            ['status' => 1, 'offset'  => '-05:00', 'label'  => '(GMT-05:00) Rio Branco', 'timezone'  => 'America/Rio_Branco'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Atlantic Time - Halifax', 'timezone'  => 'America/Halifax'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Barbados', 'timezone'  => 'America/Barbados'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Bermuda', 'timezone'  => 'Atlantic/Bermuda'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Boa Vista', 'timezone'  => 'America/Boa_Vista'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Caracas', 'timezone'  => 'America/Caracas'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Curacao', 'timezone'  => 'America/Curacao'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Grand Turk', 'timezone'  => 'America/Grand_Turk'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Guyana', 'timezone'  => 'America/Guyana'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) La Paz', 'timezone'  => 'America/La_Paz'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Manaus', 'timezone'  => 'America/Manaus'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Martinique', 'timezone'  => 'America/Martinique'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Port of Spain', 'timezone'  => 'America/Port_of_Spain'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Porto Velho', 'timezone'  => 'America/Porto_Velho'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Puerto Rico', 'timezone'  => 'America/Puerto_Rico'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Santo Domingo', 'timezone'  => 'America/Santo_Domingo'],
            ['status' => 0, 'offset'  => '-04:00', 'label'  => '(GMT-04:00) Thule', 'timezone'  => 'America/Thule'],
            ['status' => 0, 'offset'  => '-03:30', 'label'  => '(GMT-03:30) Newfoundland Time - St. Johns', 'timezone'  => 'America/St_Johns'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Araguaina', 'timezone'  => 'America/Araguaina'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Asuncion', 'timezone'  => 'America/Asuncion'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Belem', 'timezone'  => 'America/Belem'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Buenos Aires', 'timezone'  => 'America/Argentina/Buenos_Aires'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Campo Grande', 'timezone'  => 'America/Campo_Grande'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Cayenne', 'timezone'  => 'America/Cayenne'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Cuiaba', 'timezone'  => 'America/Cuiaba'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Fortaleza', 'timezone'  => 'America/Fortaleza'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Godthab', 'timezone'  => 'America/Godthab'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Maceio', 'timezone'  => 'America/Maceio'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Miquelon', 'timezone'  => 'America/Miquelon'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Montevideo', 'timezone'  => 'America/Montevideo'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Palmer', 'timezone'  => 'Antarctica/Palmer'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Paramaribo', 'timezone'  => 'America/Paramaribo'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Punta Arenas', 'timezone'  => 'America/Punta_Arenas'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Recife', 'timezone'  => 'America/Recife'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Rothera', 'timezone'  => 'Antarctica/Rothera'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Salvador', 'timezone'  => 'America/Bahia'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Santiago', 'timezone'  => 'America/Santiago'],
            ['status' => 0, 'offset'  => '-03:00', 'label'  => '(GMT-03:00) Stanley', 'timezone'  => 'Atlantic/Stanley'],
            ['status' => 0, 'offset'  => '-02:00', 'label'  => '(GMT-02:00) Noronha', 'timezone'  => 'America/Noronha'],
            ['status' => 0, 'offset'  => '-02:00', 'label'  => '(GMT-02:00) Sao Paulo', 'timezone'  => 'America/Sao_Paulo'],
            ['status' => 0, 'offset'  => '-02:00', 'label'  => '(GMT-02:00) South Georgia', 'timezone'  => 'Atlantic/South_Georgia'],
            ['status' => 0, 'offset'  => '-01:00', 'label'  => '(GMT-01:00) Azores', 'timezone'  => 'Atlantic/Azores'],
            ['status' => 0, 'offset'  => '-01:00', 'label'  => '(GMT-01:00) Cape Verde', 'timezone'  => 'Atlantic/Cape_Verde'],
            ['status' => 0, 'offset'  => '-01:00', 'label'  => '(GMT-01:00) Scoresbysund', 'timezone'  => 'America/Scoresbysund'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Abidjan', 'timezone'  => 'Africa/Abidjan'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Accra', 'timezone'  => 'Africa/Accra'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Bissau', 'timezone'  => 'Africa/Bissau'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Canary Islands', 'timezone'  => 'Atlantic/Canary'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Casablanca', 'timezone'  => 'Africa/Casablanca'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Danmarkshavn', 'timezone'  => 'America/Danmarkshavn'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Dublin', 'timezone'  => 'Europe/Dublin'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) El Aaiun', 'timezone'  => 'Africa/El_Aaiun'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Faeroe', 'timezone'  => 'Atlantic/Faroe'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) GMT (no daylight saving)', 'timezone'  => 'Etc/GMT'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Lisbon', 'timezone'  => 'Europe/Lisbon'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) London', 'timezone'  => 'Europe/London'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Monrovia', 'timezone'  => 'Africa/Monrovia'],
            ['status' => 0, 'offset'  => '+00:00', 'label'  => '(GMT+00:00) Reykjavik', 'timezone'  => 'Atlantic/Reykjavik'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Algiers', 'timezone'  => 'Africa/Algiers'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Amsterdam', 'timezone'  => 'Europe/Amsterdam'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Andorra', 'timezone'  => 'Europe/Andorra'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Berlin', 'timezone'  => 'Europe/Berlin'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Brussels', 'timezone'  => 'Europe/Brussels'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Budapest', 'timezone'  => 'Europe/Budapest'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Central European Time - Belgrade', 'timezone'  => 'Europe/Belgrade'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Central European Time - Prague', 'timezone'  => 'Europe/Prague'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Ceuta', 'timezone'  => 'Africa/Ceuta'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Copenhagen', 'timezone'  => 'Europe/Copenhagen'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Gibraltar', 'timezone'  => 'Europe/Gibraltar'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Lagos', 'timezone'  => 'Africa/Lagos'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Luxembourg', 'timezone'  => 'Europe/Luxembourg'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Madrid', 'timezone'  => 'Europe/Madrid'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Malta', 'timezone'  => 'Europe/Malta'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Monaco', 'timezone'  => 'Europe/Monaco'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Ndjamena', 'timezone'  => 'Africa/Ndjamena'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Oslo', 'timezone'  => 'Europe/Oslo'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Paris', 'timezone'  => 'Europe/Paris'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Rome', 'timezone'  => 'Europe/Rome'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Stockholm', 'timezone'  => 'Europe/Stockholm'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Tirane', 'timezone'  => 'Europe/Tirane'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Tunis', 'timezone'  => 'Africa/Tunis'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Vienna', 'timezone'  => 'Europe/Vienna'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Warsaw', 'timezone'  => 'Europe/Warsaw'],
            ['status' => 0, 'offset'  => '+01:00', 'label'  => '(GMT+01:00) Zurich', 'timezone'  => 'Europe/Zurich'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Amman', 'timezone'  => 'Asia/Amman'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Athens', 'timezone'  => 'Europe/Athens'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Beirut', 'timezone'  => 'Asia/Beirut'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Bucharest', 'timezone'  => 'Europe/Bucharest'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Cairo', 'timezone'  => 'Africa/Cairo'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Chisinau', 'timezone'  => 'Europe/Chisinau'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Damascus', 'timezone'  => 'Asia/Damascus'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Gaza', 'timezone'  => 'Asia/Gaza'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Helsinki', 'timezone'  => 'Europe/Helsinki'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Jerusalem', 'timezone'  => 'Asia/Jerusalem'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Johannesburg', 'timezone'  => 'Africa/Johannesburg'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Khartoum', 'timezone'  => 'Africa/Khartoum'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Kiev', 'timezone'  => 'Europe/Kiev'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Maputo', 'timezone'  => 'Africa/Maputo'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Moscow-01 - Kaliningrad', 'timezone'  => 'Europe/Kaliningrad'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Nicosia', 'timezone'  => 'Asia/Nicosia'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Riga', 'timezone'  => 'Europe/Riga'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Sofia', 'timezone'  => 'Europe/Sofia'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Tallinn', 'timezone'  => 'Europe/Tallinn'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Tripoli', 'timezone'  => 'Africa/Tripoli'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Vilnius', 'timezone'  => 'Europe/Vilnius'],
            ['status' => 0, 'offset'  => '+02:00', 'label'  => '(GMT+02:00) Windhoek', 'timezone'  => 'Africa/Windhoek'],
            ['status' => 0, 'offset'  => '+03:00', 'label'  => '(GMT+03:00) Baghdad', 'timezone'  => 'Asia/Baghdad'],
            ['status' => 0, 'offset'  => '+03:00', 'label'  => '(GMT+03:00) Istanbul', 'timezone'  => 'Europe/Istanbul'],
            ['status' => 0, 'offset'  => '+03:00', 'label'  => '(GMT+03:00) Minsk', 'timezone'  => 'Europe/Minsk'],
            ['status' => 0, 'offset'  => '+03:00', 'label'  => '(GMT+03:00) Moscow+00 - Moscow', 'timezone'  => 'Europe/Moscow'],
            ['status' => 0, 'offset'  => '+03:00', 'label'  => '(GMT+03:00) Nairobi', 'timezone'  => 'Africa/Nairobi'],
            ['status' => 0, 'offset'  => '+03:00', 'label'  => '(GMT+03:00) Qatar', 'timezone'  => 'Asia/Qatar'],
            ['status' => 0, 'offset'  => '+03:00', 'label'  => '(GMT+03:00) Riyadh', 'timezone'  => 'Asia/Riyadh'],
            ['status' => 0, 'offset'  => '+03:00', 'label'  => '(GMT+03:00) Syowa', 'timezone'  => 'Antarctica/Syowa'],
            ['status' => 0, 'offset'  => '+03:30', 'label'  => '(GMT+03:30) Tehran', 'timezone'  => 'Asia/Tehran'],
            ['status' => 0, 'offset'  => '+04:00', 'label'  => '(GMT+04:00) Baku', 'timezone'  => 'Asia/Baku'],
            ['status' => 0, 'offset'  => '+04:00', 'label'  => '(GMT+04:00) Dubai', 'timezone'  => 'Asia/Dubai'],
            ['status' => 0, 'offset'  => '+04:00', 'label'  => '(GMT+04:00) Mahe', 'timezone'  => 'Indian/Mahe'],
            ['status' => 0, 'offset'  => '+04:00', 'label'  => '(GMT+04:00) Mauritius', 'timezone'  => 'Indian/Mauritius'],
            ['status' => 0, 'offset'  => '+04:00', 'label'  => '(GMT+04:00) Moscow+01 - Samara', 'timezone'  => 'Europe/Samara'],
            ['status' => 0, 'offset'  => '+04:00', 'label'  => '(GMT+04:00) Reunion', 'timezone'  => 'Indian/Reunion'],
            ['status' => 0, 'offset'  => '+04:00', 'label'  => '(GMT+04:00) Tbilisi', 'timezone'  => 'Asia/Tbilisi'],
            ['status' => 0, 'offset'  => '+04:00', 'label'  => '(GMT+04:00) Yerevan', 'timezone'  => 'Asia/Yerevan'],
            ['status' => 0, 'offset'  => '+04:30', 'label'  => '(GMT+04:30) Kabul', 'timezone'  => 'Asia/Kabul'],
            ['status' => 0, 'offset'  => '+05:00', 'label'  => '(GMT+05:00) Aqtau', 'timezone'  => 'Asia/Aqtau'],
            ['status' => 0, 'offset'  => '+05:00', 'label'  => '(GMT+05:00) Aqtobe', 'timezone'  => 'Asia/Aqtobe'],
            ['status' => 0, 'offset'  => '+05:00', 'label'  => '(GMT+05:00) Ashgabat', 'timezone'  => 'Asia/Ashgabat'],
            ['status' => 0, 'offset'  => '+05:00', 'label'  => '(GMT+05:00) Dushanbe', 'timezone'  => 'Asia/Dushanbe'],
            ['status' => 0, 'offset'  => '+05:00', 'label'  => '(GMT+05:00) Karachi', 'timezone'  => 'Asia/Karachi'],
            ['status' => 0, 'offset'  => '+05:00', 'label'  => '(GMT+05:00) Kerguelen', 'timezone'  => 'Indian/Kerguelen'],
            ['status' => 0, 'offset'  => '+05:00', 'label'  => '(GMT+05:00) Maldives', 'timezone'  => 'Indian/Maldives'],
            ['status' => 0, 'offset'  => '+05:00', 'label'  => '(GMT+05:00) Mawson', 'timezone'  => 'Antarctica/Mawson'],
            ['status' => 0, 'offset'  => '+05:00', 'label'  => '(GMT+05:00) Moscow+02 - Yekaterinburg', 'timezone'  => 'Asia/Yekaterinburg'],
            ['status' => 0, 'offset'  => '+05:00', 'label'  => '(GMT+05:00) Tashkent', 'timezone'  => 'Asia/Tashkent'],
            ['status' => 0, 'offset'  => '+05:30', 'label'  => '(GMT+05:30) Colombo', 'timezone'  => 'Asia/Colombo'],
            ['status' => 1, 'offset'  => '+05:30', 'label'  => '(GMT+05:30) India Standard Time', 'timezone'  => 'Asia/Kolkata'],
            ['status' => 0, 'offset'  => '+05:45', 'label'  => '(GMT+05:45) Kathmandu', 'timezone'  => 'Asia/Kathmandu'],
            ['status' => 0, 'offset'  => '+06:00', 'label'  => '(GMT+06:00) Almaty', 'timezone'  => 'Asia/Almaty'],
            ['status' => 0, 'offset'  => '+06:00', 'label'  => '(GMT+06:00) Bishkek', 'timezone'  => 'Asia/Bishkek'],
            ['status' => 0, 'offset'  => '+06:00', 'label'  => '(GMT+06:00) Chagos', 'timezone'  => 'Indian/Chagos'],
            ['status' => 0, 'offset'  => '+06:00', 'label'  => '(GMT+06:00) Dhaka', 'timezone'  => 'Asia/Dhaka'],
            ['status' => 0, 'offset'  => '+06:00', 'label'  => '(GMT+06:00) Moscow+03 - Omsk', 'timezone'  => 'Asia/Omsk'],
            ['status' => 0, 'offset'  => '+06:00', 'label'  => '(GMT+06:00) Thimphu', 'timezone'  => 'Asia/Thimphu'],
            ['status' => 0, 'offset'  => '+06:00', 'label'  => '(GMT+06:00) Vostok', 'timezone'  => 'Antarctica/Vostok'],
            ['status' => 0, 'offset'  => '+06:30', 'label'  => '(GMT+06:30) Cocos', 'timezone'  => 'Indian/Cocos'],
            ['status' => 0, 'offset'  => '+06:30', 'label'  => '(GMT+06:30) Rangoon', 'timezone'  => 'Asia/Yangon'],
            ['status' => 0, 'offset'  => '+07:00', 'label'  => '(GMT+07:00) Bangkok', 'timezone'  => 'Asia/Bangkok'],
            ['status' => 0, 'offset'  => '+07:00', 'label'  => '(GMT+07:00) Christmas', 'timezone'  => 'Indian/Christmas'],
            ['status' => 0, 'offset'  => '+07:00', 'label'  => '(GMT+07:00) Davis', 'timezone'  => 'Antarctica/Davis'],
            ['status' => 0, 'offset'  => '+07:00', 'label'  => '(GMT+07:00) Hanoi', 'timezone'  => 'Asia/Saigon'],
            ['status' => 0, 'offset'  => '+07:00', 'label'  => '(GMT+07:00) Hovd', 'timezone'  => 'Asia/Hovd'],
            ['status' => 0, 'offset'  => '+07:00', 'label'  => '(GMT+07:00) Jakarta', 'timezone'  => 'Asia/Jakarta'],
            ['status' => 0, 'offset'  => '+07:00', 'label'  => '(GMT+07:00) Moscow+04 - Krasnoyarsk', 'timezone'  => 'Asia/Krasnoyarsk'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Brunei', 'timezone'  => 'Asia/Brunei'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) China Time - Beijing', 'timezone'  => 'Asia/Shanghai'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Choibalsan', 'timezone'  => 'Asia/Choibalsan'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Hong Kong', 'timezone'  => 'Asia/Hong_Kong'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Kuala Lumpur', 'timezone'  => 'Asia/Kuala_Lumpur'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Macau', 'timezone'  => 'Asia/Macau'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Makassar', 'timezone'  => 'Asia/Makassar'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Manila', 'timezone'  => 'Asia/Manila'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Moscow+05 - Irkutsk', 'timezone'  => 'Asia/Irkutsk'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Singapore', 'timezone'  => 'Asia/Singapore'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Taipei', 'timezone'  => 'Asia/Taipei'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Ulaanbaatar', 'timezone'  => 'Asia/Ulaanbaatar'],
            ['status' => 0, 'offset'  => '+08:00', 'label'  => '(GMT+08:00) Western Time - Perth', 'timezone'  => 'Australia/Perth'],
            ['status' => 0, 'offset'  => '+08:30', 'label'  => '(GMT+08:30) Pyongyang', 'timezone'  => 'Asia/Pyongyang'],
            ['status' => 0, 'offset'  => '+09:00', 'label'  => '(GMT+09:00) Dili', 'timezone'  => 'Asia/Dili'],
            ['status' => 0, 'offset'  => '+09:00', 'label'  => '(GMT+09:00) Jayapura', 'timezone'  => 'Asia/Jayapura'],
            ['status' => 0, 'offset'  => '+09:00', 'label'  => '(GMT+09:00) Moscow+06 - Yakutsk', 'timezone'  => 'Asia/Yakutsk'],
            ['status' => 0, 'offset'  => '+09:00', 'label'  => '(GMT+09:00) Palau', 'timezone'  => 'Pacific/Palau'],
            ['status' => 0, 'offset'  => '+09:00', 'label'  => '(GMT+09:00) Seoul', 'timezone'  => 'Asia/Seoul'],
            ['status' => 0, 'offset'  => '+09:00', 'label'  => '(GMT+09:00) Tokyo', 'timezone'  => 'Asia/Tokyo'],
            ['status' => 0, 'offset'  => '+09:30', 'label'  => '(GMT+09:30) Central Time - Darwin', 'timezone'  => 'Australia/Darwin'],
            ['status' => 0, 'offset'  => '+10:00', 'label'  => '(GMT+10:00) Dumont D\'Urville', 'timezone'  => 'Antarctica/DumontDUrville'],
            ['status' => 0, 'offset'  => '+10:00', 'label'  => '(GMT+10:00) Eastern Time - Brisbane', 'timezone'  => 'Australia/Brisbane'],
            ['status' => 0, 'offset'  => '+10:00', 'label'  => '(GMT+10:00) Guam', 'timezone'  => 'Pacific/Guam'],
            ['status' => 0, 'offset'  => '+10:00', 'label'  => '(GMT+10:00) Moscow+07 - Vladivostok', 'timezone'  => 'Asia/Vladivostok'],
            ['status' => 0, 'offset'  => '+10:00', 'label'  => '(GMT+10:00) Port Moresby', 'timezone'  => 'Pacific/Port_Moresby'],
            ['status' => 0, 'offset'  => '+10:00', 'label'  => '(GMT+10:00) Truk', 'timezone'  => 'Pacific/Chuuk'],
            ['status' => 0, 'offset'  => '+10:30', 'label'  => '(GMT+10:30) Central Time - Adelaide', 'timezone'  => 'Australia/Adelaide'],
            ['status' => 0, 'offset'  => '+11:00', 'label'  => '(GMT+11:00) Casey', 'timezone'  => 'Antarctica/Casey'],
            ['status' => 0, 'offset'  => '+11:00', 'label'  => '(GMT+11:00) Eastern Time - Hobart', 'timezone'  => 'Australia/Hobart'],
            ['status' => 0, 'offset'  => '+11:00', 'label'  => '(GMT+11:00) Eastern Time - Melbourne, Sydney', 'timezone'  => 'Australia/Sydney'],
            ['status' => 0, 'offset'  => '+11:00', 'label'  => '(GMT+11:00) Efate', 'timezone'  => 'Pacific/Efate'],
            ['status' => 0, 'offset'  => '+11:00', 'label'  => '(GMT+11:00) Guadalcanal', 'timezone'  => 'Pacific/Guadalcanal'],
            ['status' => 0, 'offset'  => '+11:00', 'label'  => '(GMT+11:00) Kosrae', 'timezone'  => 'Pacific/Kosrae'],
            ['status' => 0, 'offset'  => '+11:00', 'label'  => '(GMT+11:00) Moscow+08 - Magadan', 'timezone'  => 'Asia/Magadan'],
            ['status' => 0, 'offset'  => '+11:00', 'label'  => '(GMT+11:00) Norfolk', 'timezone'  => 'Pacific/Norfolk'],
            ['status' => 0, 'offset'  => '+11:00', 'label'  => '(GMT+11:00) Noumea', 'timezone'  => 'Pacific/Noumea'],
            ['status' => 0, 'offset'  => '+11:00', 'label'  => '(GMT+11:00) Ponape', 'timezone'  => 'Pacific/Pohnpei'],
            ['status' => 0, 'offset'  => '+12:00', 'label'  => '(GMT+12:00) Funafuti', 'timezone'  => 'Pacific/Funafuti'],
            ['status' => 0, 'offset'  => '+12:00', 'label'  => '(GMT+12:00) Kwajalein', 'timezone'  => 'Pacific/Kwajalein'],
            ['status' => 0, 'offset'  => '+12:00', 'label'  => '(GMT+12:00) Majuro', 'timezone'  => 'Pacific/Majuro'],
            ['status' => 0, 'offset'  => '+12:00', 'label'  => '(GMT+12:00) Moscow+09 - Petropavlovsk-Kamchatskiy', 'timezone'  => 'Asia/Kamchatka'],
            ['status' => 0, 'offset'  => '+12:00', 'label'  => '(GMT+12:00) Nauru', 'timezone'  => 'Pacific/Nauru'],
            ['status' => 0, 'offset'  => '+12:00', 'label'  => '(GMT+12:00) Tarawa', 'timezone'  => 'Pacific/Tarawa'],
            ['status' => 0, 'offset'  => '+12:00', 'label'  => '(GMT+12:00) Wake', 'timezone'  => 'Pacific/Wake'],
            ['status' => 0, 'offset'  => '+12:00', 'label'  => '(GMT+12:00) Wallis', 'timezone'  => 'Pacific/Wallis'],
            ['status' => 0, 'offset'  => '+13:00', 'label'  => '(GMT+13:00) Auckland', 'timezone'  => 'Pacific/Auckland'],
            ['status' => 0, 'offset'  => '+13:00', 'label'  => '(GMT+13:00) Enderbury', 'timezone'  => 'Pacific/Enderbury'],
            ['status' => 0, 'offset'  => '+13:00', 'label'  => '(GMT+13:00) Fakaofo', 'timezone'  => 'Pacific/Fakaofo'],
            ['status' => 0, 'offset'  => '+13:00', 'label'  => '(GMT+13:00) Fiji', 'timezone'  => 'Pacific/Fiji'],
            ['status' => 0, 'offset'  => '+13:00', 'label'  => '(GMT+13:00) Tongatapu', 'timezone'  => 'Pacific/Tongatapu'],
            ['status' => 0, 'offset'  => '+14:00', 'label'  => '(GMT+14:00) Apia', 'timezone'  => 'Pacific/Apia'],
            ['status' => 0, 'offset'  => '+14:00', 'label'  => '(GMT+14:00) Kiritimati', 'timezone'  => 'Pacific/Kiritimati']
        ];
        Timezone::truncate();
        Timezone::insert($timezoneList);
    }
}
